### ISSUE TITLE
Addons To-Do List

### ISSUE THREAD

**Issue by j-rockwell** [ares-network/ares-addons#1]
### Essentials
- [x] - /ban <player> [reason] [-s] - Ban a player from the server
- [x] - /tempban <player> <timeframe> [reason] [-s] - Temporarily ban a player from the server
- [x] - /blacklist <player> [reason] [-s] - Blacklist a player from the server (IP Ban)
- [x] - /kick <player> [reason] [-s] - Kick a player from the server
- [x] - /mute <player> [reason] [-s] - Mute a player on the server
- [x] - /tempmute <player> <timeframe> [reason] [-s] - Temporarily mute a player on the server
- [x] - /unban <player> - Unban a player from the server
- [x] - /unmute <player> - Unmute a player on the server
- [x] - /unblacklist <player> - Unblacklist a player from the server
- [x] - /lookup <player> - Displays a players information and a list of notes on their account
- [x] - /broadcast <message> - Broadcast anonymously
- [x] - /pbroadcast <message> - Broadcast with username
- [x] - /clear [player] - Clear an inventory
- [x] - /enchant <hand/armor> <enchantment> <level> - Enchant item or armor
- [x] - /gamemode <gamemode> [player] - Update gamemode
- [x] - /heal [player] - Heal a player
- [x] - /invsee <player> - View full player statistics and inventory live
- [x] - /item <item> [amount] - Spawn a specified item
- [x] - /list - View all online players
- [x] - /rename <name> - Rename the item in your hand
- [x] - /repair - Repair the item in your hand
- [x] - /teleport <player> - Teleport to a player
- [x] - /teleport <player> <player> - Teleport a player to another player
- [x] - /teleport <x> <y> <z> - Teleport to coordinates
- [x] - /teleport <x> <y> <z> <world> - Teleport to coordinates in a different world
- [x] - /world <name> - Teleport to the spawn of a specified world
- [x] - /warp create <name> - Create a new warp
- [x] - /warp delete <name> - Delete a warp
- [x] - /warp list - List warps
- [x] - /warp <name> - Teleport to a warp
- [x] - /weather <clear/rain/thunder> - Toggle weather state
- [x] - /vanish - Toggle vanish state
- [x] - /helpop <message> - Send a help request for admins to see
- [x] - /report <player> <reason> - Send a report to the staff for a player

### Humbug
**Anti-Grief:**
- [x] - Disable block explosions
- [x] - Disable entity block changes
- [x] - Disable fire spread
- [x] - Disable leaf decay
- [x] - Disable cobblestole generators
- [x] - Disable bed bombs

~~**Minecart Elevators**~~

~~**Enchantment/Potion Limits**~~

~~**Modified Knockback**~~

~~**Mob Stacking**~~

**Combat Mods**
- [x] - Combat Tag
- [x] - Enderpearl Cooldown
- [x] - Crapple Cooldown
- [x] - Gapple Cooldown
~~_Render UI from this addon_~~

**Chat Restrictions**
- [ ] - Disable posting links

### Tips
