### ISSUE TITLE
Final To-Do List

### ISSUE THREAD

**Issue by j-rockwell** [ares-network/ares-addons#2]
Web Bridge To-Do
- [x] Fix ClassCastException @ WebAccount:43 (Double cannot be cast to Long)
- [x] Fix Linkage Errors
- [x] Implement account resetting
- [x] Add confirmation emails

**Tuesday**
- [x] /network kick command
- [x] Rewrite snitch log display
- [x] Rewrite network show command
- [x] Disable posting links for players without the permission (+ assign permission to ranks)
- [x] Fix combat loggers spawning
- [x] If an account is new teleport them to spawn (player.hasPlayedBefore)

**Wednesday**
- [x] Prevent Acid Blocks from ticking damage in Bastion fields they aren't a part of
- [x] Allow staff to see all chat messages
- [x] Add alt username lookup in /lookup command
- [x] Test alt/vpn bypasses with Rixxlon
- [x] Delete reports/requests upon being clicked
- [x] Create factory recipes
- [x] Add HCFR Knockback values
- [x] Install & Configure AAC
- [x] Add Admin Settings
- [x] Fix prison pearled players that are set free not being sent to Spawn
- [x] Remove permissions for Prison Pearled players
- [x] Create Cayden resource pack

**Thursday**
- [x] Find a way to make alt account notifications configurable for staff
- [x] Create kit command
- [x] Rebalance Strength/Regeneration
- [x] Fix ProtocolLib packet spam
- [x] Fix players not going to spawn upon initial join
- [x] Reset all timers upon respawning
- [x] Fix bastion range being huge
- [x] Fix slain invsee players spamming the not available message
- [x] Clean up /r/Ares
- [x] Test AAC
- [x] Find SOME WAY to compile 1.8.8 Paper (Likely Taco)

**Friday**
- [x] Film Cayden fight video
- [x] Fix combat tag not refreshing, overlapping existing
- [x] Disable /tell command
- [x] Disable expired prison pearls from being thrown (drop player head?)
- [x] Implement dynamic claim loading/unloading
- [x] Add ChatColor.RESET to item names in death messages
- [x] Fix bug with Cobble Monster prevention causing block physics to suck ass

**Saturday**
- [x] Release Cayden fight video at 12:00PM PST
- [x] Purchase & Configure G-Suite (partner@playares.com, support@playares.com)
- [x] Begin website development (Front page, Tutorial page, routing links for Reddit, Discord)
- [x] Release a detailed reddit post on /r/Ares

**Sunday**
- [x] Discuss nerfing crates
- [x] Add chat rate limiter
- [x] Scale Prison Pearl bans based off of rank permissions (Silver 14, Gold 12, Sapph 10, Emerald & Ruby 7)
- [x] Permission based starter kits with cooldowns per give (use rewards system)
- [x] Paywall bottling EXP
- [x] Add time divider based on ranks

### FINAL WEEK - BUG TESTING STAGES

**Monday**
- [x] Fix https://pastebin.com/vB1RTRSX

**Tuesday**
- [x] Complete Web Bridge

**Wednesday**
- [x] Update BuyCraft perks

**Thursday**
- [x] Test Pearl Protection
- [x] Fix expired enderpearls not being deleted from database
- [x] Test Combat Logger Spawning
- [x] Fix fortification with placed stone not subtracting twice
- [x] Fix starter kits not being applied (Silver at least)

**Friday**

**Saturday**
- [x] Release promotional trailer
- [x] Fix Acid not ticking damage
- [x] Create Server Tutorials
- [x] Fix claims not protecting double chests
- [x] Add network name to claim info message if it is owned by the viewing player
- [x] Add notifier that an Acid Block is being blocked by a bastion when created and in /acid info
- [x] Add Kit Signs
- [x] Add option to toggle Prison Pearl and Pearl Protection off
- [x] Update website
- [ ] Add alternative spawn handling for KitMap
- [ ] Setup Spawn
- [ ] Fully configure the server for production
- [ ] Add Bungee, Configure a separate Development server
- [ ] Pre-gen The Nether
- [ ] Pre-gen The End
- [ ] Regen map
