### ISSUE TITLE
The (real) Final To-Do List

### ISSUE THREAD

**Issue by j-rockwell** [ares-network/ares-addons#3]
Thursday
~~Convert reports and requests to database objects and save/load database~~
~~Re-add /lookup command~~
~~Create chat notification for reports and requests~~
~~Setup Proxy~~
~~Write hub queue plugin~~

Friday
~~Configure Kit Map~~
~~Launch Kit Map~~
~~Bug Fixes: https://github.com/ares-network/ares-addons/issues/4~~
~~Add custom death messages~~
~~Improve Prison Pearl Create/Free Messages~~
Add product images to J BAR Website
Work on Bavna Issue

Saturday
~~Prison Pearl & Claim Testing~~
~~Disable join/leave notifications in the Hub, add fancy premium join messages~~
~~Disable movement cancel for non-verified staff~~
~~Reimplement Restart Notification in HUD~~
~~Add in-game stat tracking
	- Kills
	- Deaths~~

Sunday
~~Bastion & Acid Testing~~
~~Reimplement Ares Player Settings GUI~~

Monday
~~Release trailers~~
~~Factory & Mining Testing/Balancing~~

Tuesday
~~Announce Q&A~~
~~Remove stat tracking for now~~
~~Add command to view all your nearby snitches~~
~~Make exiting the end randomly teleport you~~
~~Disable interact check kicking players~~
~~Re-add 'FoundOreEvent' and cancel it if it's a claimed block~~
~~Add color support to found ore messages~~
~~Add command/gui to view all snitches connected to your network~~
~~Fix block physics being blocked by an event~~
~~Disable combat loggers spawning for staff/players in creative~~
~~Harden Server Security~~

Wednesday
~~Allow claimed blocks to be broken by players with a permission~~
~~Prevent Nether Portals from forming in Bastion fields~~
~~Only allow portal creation by users in bastion fields they own~~
~~Add vanished display to the HUD~~
~~Add ViaVersion to Lobby~~
~~Tweak knockback and add vertical~~

Server preparation
- [x] Setup Starter Kits
- [x] Confirm Factory Balancing
- [x] Update permissions
- [x] Reconfigure Render Distances
- [x] Add mooshrooms to mobstacker
- [ ] Implement the half-assed Staff Regions
- [x] Test & tweak knockback
- [x] Fix NPE @ ClaimListener:471
- [x] Make sure network default settings are configured correctly
